### ISSUE TITLE
Ruby Logger format

### ISSUE THREAD

**Issue by penntaylor** [tstack/lnav-config#1]
I just committed a repo with a Ruby Logger format. Not sure whether it's appropriate for inclusion in `lnav-config` since it's just a single format. Is there some other central location for announcing new publicly-available formats?

https://github.com/penntaylor/lnav-ruby-logger-format

**Comment by tstack** [comment]
I think it's fine to add to the list.  You can also send a message to the mailing list:

 https://groups.google.com/forum/#!forum/lnav
